version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inf236-frontend
    ports:
      - 7777:80
      
  nginx:
    image: nginx:alpine
    container_name: nginx-app
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - frontend
  
