# Generated by Django 4.2.11 on 2024-06-15 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motor_id', models.CharField(default='', max_length=100)),
                ('camion_id', models.CharField(default='', max_length=100)),
                ('asign_date', models.CharField(default='', max_length=100)),
                ('unassign_date', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Camion',
            fields=[
                ('id_camion', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('n_serie', models.CharField(default='', max_length=256)),
                ('placa', models.CharField(default='', max_length=256)),
                ('estado', models.CharField(default='', max_length=256)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('durabilidad', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('motor_id', models.CharField(blank=True, default='', max_length=100)),
                ('incident_date', models.CharField(blank=True, default='', max_length=100)),
                ('problem_description', models.TextField(blank=True, default='')),
                ('mechanics_associated', models.TextField(blank=True, default='')),
                ('work_to_do', models.TextField(blank=True, default='')),
                ('mechanic_id', models.CharField(blank=True, default='', max_length=100)),
                ('start_date', models.CharField(blank=True, default='', max_length=100)),
                ('end_date', models.CharField(blank=True, default='', max_length=100)),
                ('solved', models.BooleanField(default=False)),
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Motor',
            fields=[
                ('id_motor', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('n_serie', models.CharField(default='', max_length=256)),
                ('operativo', models.BooleanField(default=True)),
                ('tiempo_en_uso', models.IntegerField(blank=True, null=True)),
                ('fecha_inicio', models.DateTimeField(default=None)),
                ('durabilidad', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('rut', models.CharField(default='', max_length=256)),
                ('contrasena', models.CharField(default='', max_length=256)),
                ('nombre', models.CharField(default='', max_length=256)),
                ('apellido', models.CharField(default='', max_length=256)),
                ('fecha_registro', models.DateTimeField(default=None)),
                ('rol', models.CharField(default='', max_length=256)),
                ('turno', models.CharField(default='', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Sistema',
            fields=[
                ('id_sistema', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='', max_length=256)),
                ('n_serie', models.CharField(default='', max_length=256)),
                ('motor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inf236backend.motor')),
            ],
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id_incidencia', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('descripcion_problema', models.TextField()),
                ('descripcion_trabajo_necesario', models.TextField()),
                ('fecha_incidencia', models.DateTimeField(default=None)),
                ('fecha_inicio_trabajo', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin_trabajo', models.DateTimeField(blank=True, null=True)),
                ('solucionado', models.BooleanField(default=False)),
                ('motor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inf236backend.motor')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inf236backend.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id_componente', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('n_serie', models.CharField(default='', max_length=256)),
                ('fecha_inicio', models.DateTimeField(default=None)),
                ('durabilidad', models.IntegerField(blank=True, null=True)),
                ('sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inf236backend.sistema')),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionMotorCamion',
            fields=[
                ('id_asignacion', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateTimeField(default=None)),
                ('fecha_desasignacion', models.DateTimeField(blank=True, null=True)),
                ('camion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inf236backend.camion')),
                ('motor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inf236backend.motor')),
            ],
        ),
    ]
