# Generated by Django 4.2.11 on 2024-10-07 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inf236backend', '0001_initial'),
    ]

    operations = [
    ]
