# Generated by Django 4.2.11 on 2024-10-07 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inf236backend', '0002_camion_motor_operativo_motor_tiempo_en_uso_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motor_id', models.CharField(default='', max_length=100)),
                ('camion_id', models.CharField(default='', max_length=100)),
                ('asign_date', models.CharField(default='', max_length=100)),
                ('unassign_date', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('motor_id', models.CharField(blank=True, default='', max_length=100)),
                ('incident_date', models.CharField(blank=True, default='', max_length=100)),
                ('problem_description', models.TextField(blank=True, default='')),
                ('mechanics_associated', models.TextField(blank=True, default='')),
                ('work_to_do', models.TextField(blank=True, default='')),
                ('mechanic_id', models.CharField(blank=True, default='', max_length=100)),
                ('start_date', models.CharField(blank=True, default='', max_length=100)),
                ('end_date', models.CharField(blank=True, default='', max_length=100)),
                ('solved', models.BooleanField(default=False)),
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('rut', models.CharField(default='', max_length=256)),
                ('contrasena', models.CharField(default='', max_length=256)),
                ('nombre', models.CharField(default='', max_length=256)),
                ('apellido', models.CharField(default='', max_length=256)),
                ('fecha_registro', models.DateTimeField(default=None)),
                ('rol', models.CharField(default='', max_length=256)),
                ('turno', models.CharField(default='', max_length=256)),
            ],
        ),
        migrations.RemoveField(
            model_name='asignacionmotorcamion',
            name='id',
        ),
        migrations.RemoveField(
            model_name='camion',
            name='id',
        ),
        migrations.RemoveField(
            model_name='motor',
            name='id',
        ),
        migrations.AddField(
            model_name='asignacionmotorcamion',
            name='id_asignacion',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='camion',
            name='durabilidad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='camion',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='camion',
            name='id_camion',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='camion',
            name='n_serie',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='camion',
            name='placa',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='motor',
            name='durabilidad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motor',
            name='fecha_inicio',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='motor',
            name='id_motor',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='asignacionmotorcamion',
            name='fecha_asignacion',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='camion',
            name='estado',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='motor',
            name='n_serie',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.CreateModel(
            name='Sistema',
            fields=[
                ('id_sistema', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='', max_length=256)),
                ('n_serie', models.CharField(default='', max_length=256)),
                ('motor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inf236backend.motor')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('record_id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('problem_description', models.TextField()),
                ('record_date', models.DateTimeField(default=None)),
                ('camion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inf236backend.camion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inf236backend.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id_incidencia', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('descripcion_problema', models.TextField()),
                ('descripcion_trabajo_necesario', models.TextField()),
                ('fecha_incidencia', models.DateTimeField(default=None)),
                ('fecha_inicio_trabajo', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin_trabajo', models.DateTimeField(blank=True, null=True)),
                ('solucionado', models.BooleanField(default=False)),
                ('motor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inf236backend.motor')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inf236backend.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id_componente', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('n_serie', models.CharField(default='', max_length=256)),
                ('fecha_inicio', models.DateTimeField(default=None)),
                ('durabilidad', models.IntegerField(blank=True, null=True)),
                ('sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inf236backend.sistema')),
            ],
        ),
    ]
