# Generated by Django 4.2.11 on 2024-11-17 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inf236backend', '0002_initial'),
    ]

    operations = [
    ]
