# Generated by Django 4.2.11 on 2024-10-07 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inf236backend', '0002_auto_20241007_1708'),
    ]

    operations = [
    ]
