# Generated by Django 4.2.11 on 2024-10-20 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inf236backend', '0003_auto_20241020_0128'),
    ]

    operations = [
    ]
