# Generated by Django 4.2.11 on 2024-06-28 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inf236backend', '0003_delete_asign_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='componente',
            name='nombre',
            field=models.CharField(default='', max_length=256),
        ),
    ]
