# Generated by Django 4.2.11 on 2024-06-28 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inf236backend', '0004_componente_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidencia',
            name='usuario',
        ),
        migrations.AddField(
            model_name='incidencia',
            name='descripcion_trabajo_hecho',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='mecanico_asignado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inf236backend.usuario'),
        ),
        migrations.AlterField(
            model_name='camion',
            name='durabilidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='camion',
            name='estado',
            field=models.CharField(default='Operativo', max_length=256),
        ),
        migrations.AlterField(
            model_name='camion',
            name='n_serie',
            field=models.CharField(default='XXX', max_length=256),
        ),
        migrations.AlterField(
            model_name='camion',
            name='placa',
            field=models.CharField(default='Placa', max_length=256),
        ),
        migrations.AlterField(
            model_name='componente',
            name='durabilidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='componente',
            name='n_serie',
            field=models.CharField(default='XXX', max_length=256),
        ),
        migrations.AlterField(
            model_name='componente',
            name='nombre',
            field=models.CharField(default='Nombre', max_length=256),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='descripcion_problema',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='descripcion_trabajo_necesario',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='mecanicos_asociados',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='motor',
            name='durabilidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='motor',
            name='n_serie',
            field=models.CharField(default='XXX', max_length=256),
        ),
        migrations.AlterField(
            model_name='motor',
            name='tiempo_en_uso',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sistema',
            name='n_serie',
            field=models.CharField(default='XXX', max_length=256),
        ),
        migrations.AlterField(
            model_name='sistema',
            name='nombre',
            field=models.CharField(default='Nombre', max_length=256),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='apellido',
            field=models.CharField(default='Apellido', max_length=256),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='contrasena',
            field=models.CharField(default='Contrasena', max_length=256),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(default='Nombre', max_length=256),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(default='mecanico', max_length=256),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rut',
            field=models.CharField(default='RUT', max_length=256),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='turno',
            field=models.CharField(default='4x7', max_length=256),
        ),
    ]
