# Generated by Django 4.2.11 on 2024-10-22 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inf236backend', '0004_auto_20241020_0153'),
    ]

    operations = [
    ]
