# Generated by Django 4.2.11 on 2024-10-22 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inf236backend', '0005_auto_20241022_1852'),
    ]

    operations = [
    ]
