# Generated by Django 4.2.11 on 2024-06-28 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inf236backend', '0005_remove_incidencia_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidencia',
            name='motor',
        ),
        migrations.AddField(
            model_name='incidencia',
            name='camion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inf236backend.camion'),
            preserve_default=False,
        ),
    ]
