# Generated by Django 4.2.11 on 2024-06-29 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inf236backend', '0006_remove_incidencia_motor_incidencia_camion'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='motor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inf236backend.motor'),
        ),
    ]
